const propert_man = [
    {
        "id": 1,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Recently renovated lobby and fitness center, offering residents a welcoming atmosphere.",      
      },
  {
        "id": 2,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Close to downtown, pet-friendly policies.",      
      },
  {
        "id": 3,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Recently renovated lobby and fitness center, offering residents a welcoming atmosphere.",      
      },
  {
        "id": 4,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Close to downtown, pet-friendly policies.",      
      },
  {
        "id": 5,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Recently renovated lobby and fitness center, offering residents a welcoming atmosphere.",      
      },
  {
        "id": 6,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Close to downtown, pet-friendly policies.",      
      },
  {
        "id": 7,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Recently renovated lobby and fitness center, offering residents a welcoming atmosphere.",      
      },
  {
        "id": 8,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Recently renovated lobby and fitness center, offering residents a welcoming atmosphere.",      
      },
  {
        "id": 9,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Recently renovated lobby and fitness center, offering residents a welcoming atmosphere.",      
      },
  {
        "id": 10,
        "property_name": "John Smith",
        "city":"thane",
        "location":"thane",
        "total_unit": "11",
        "description": "Recently renovated lobby and fitness center, offering residents a welcoming atmosphere.",      
      },
]

export default propert_man